## 计算图
- 将代码分解成操作子
- 将计算表示成一个无环图
- 显示构造
- 隐示构造

## 自动求导的两种模式
- 链式法则
- 正向累积 （先算$\frac{\partial{u_2}}{\partial{u_1}}$）
- 反向累积（反向传递）(先算$\frac{\partial{y}}{\partial{u_n}}$)

## 复杂度
计算复杂度和内存复杂度O(n)

In [2]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [ ]:
x.requires_grad_(True)
x.grad #默认None

In [4]:
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [5]:
# 调用反向传播函数来自动计算y关于x每个分量的梯度
y.backward()
x.grad # 计算得到的梯度

tensor([ 0.,  4.,  8., 12.])

In [6]:
x.grad == 4 * x # 计算得到的梯度与手动计算的梯度相同

tensor([True, True, True, True])

In [7]:
# 在默认情况下，pytorch会累积梯度，需要清除之前的值
x.grad.zero_()
y = x.sum()
y.backward()
x.grad  

tensor([1., 1., 1., 1.])