In [82]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y , x * y , x / y , x ** y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [83]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [84]:
x[3]

tensor(3)

In [85]:
len(x)

4

In [86]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [87]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [88]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [89]:
A = torch.arange(20,dtype = torch.float32).reshape(5, 4)
B = A.clone()
A , A + B 

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [90]:
# 哈达玛积 -- 按元素乘法
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [91]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
X + a , (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [92]:
x = torch.arange(4,dtype = torch.float32)
x , x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [93]:
A = torch.arange(20*2,dtype = torch.float32).reshape(2, 5, 4)
A, A.shape, A.sum()

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 torch.Size([2, 5, 4]),
 tensor(780.))

In [94]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0.shape, A_sum_axis0

(torch.Size([5, 4]),
 tensor([[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]))

In [95]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1.shape, A_sum_axis1

(torch.Size([2, 4]),
 tensor([[ 40.,  45.,  50.,  55.],
         [140., 145., 150., 155.]]))

In [96]:
A.sum(axis=[0, 1])

tensor([180., 190., 200., 210.])

In [97]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [104]:
A = torch.arange(20*2).reshape(2, 5, 4)
A.shape, A.sum()

(torch.Size([2, 5, 4]), tensor(780))

In [105]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0.shape, A_sum_axis0

(torch.Size([5, 4]),
 tensor([[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]))

In [106]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1.shape, A_sum_axis1

(torch.Size([2, 4]),
 tensor([[ 40,  45,  50,  55],
         [140, 145, 150, 155]]))

In [107]:
A.sum(axis=[0, 1]).shape

torch.Size([4])

In [110]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
A.mean(), A.sum() / A.numel()

(tensor(9.5000), tensor(9.5000))

In [111]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))